server:
  port: 8005
spring:
  application:
    name: demo-consumer
  boot:
    admin:
      client:
        instance:
          service-base-url: ${spring.application.name}
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #样本采集量
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: true