server:
  port: 8020
spring:
  application:
    name: demo-config
  #使用本地配置文件
  profiles:
    active: native
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    config:
      server:
        native:
          searchLocations: classpath:/config
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: adminpassword
management:
  endpoints:
    web:
      exposure:
        include: "*"